part of 'app_pages.dart';

abstract class AppRoutes {
  static const notFound = '/not-found';
  static const splash = '/splash';
  static const login = '/login';
  static const home = '/home';
  static const chat = '/chat';
  static const chatNotification = '/chat_notification';
  static const chatSetup = '/chat_setup';
  static const chatSearchText = '/chat_search_text';
  static const chatSearchImage = '/chat_search_image';
  static const chatSearchVideo = '/chat_searh_video';
  static const chatSearchFile = '/chat_searh_File';
  static const addContactsMethod = '/add_contacts_method';
  static const addContactsBySearch = '/add_contacts_by_search';
  static const userProfilePanel = '/user_profile_panel';
  static const personalInfo = '/personal_info';
  static const friendSetup = '/friend_setup';
  static const setFriendRemark = '/set_friend_remark';
  static const sendVerificationApplication = '/send_verification_application';
  static const groupProfilePanel = '/group_profile_panel';
  static const myInfo = '/my_info';
  static const myTeam = '/my_team';
  static const editMyInfo = '/edit_my_info';
  static const accountSetup = '/account_setup';
  static const blacklist = '/blacklist';
  static const languageSetup = '/language_setup';
  static const aboutUs = '/about_us';
  static const groupChatSetup = '/group_chat_setup';
  static const groupManage = '/group_manage';
  static const editGroupName = '/edit_group_name';
  static const groupMemberList = '/group_member_list';
  static const groupQrcode = '/group_qrcode';
  static const friendRequests = '/friend_requests';
  static const processFriendRequests = '/process_friend_requests';
  static const groupRequests = '/group_requests';
  static const processGroupRequests = '/process_group_requests';
  static const friendList = '/friend_list';
  static const groupList = '/group_list';
  static const selectContacts = '/select_contacts';
  static const selectContactsFromFriends = '/select_contacts_from_friends';
  static const selectContactsFromGroup = '/select_contacts_from_group';
  static const selectContactsFromSearch = '/select_contacts_from_search';
  static const createGroup = '/create_group';
  static const globalSearch = '/global_search';
  static const expandChatHistory = '/expand_chat_history';
  static const register = '/register';
  static const verifyPhone = '/verify_phone';
  static const setPassword = '/set_password';
  static const setSelfInfo = '/set_self_info';
  static const forgetPassword = '/forget_password';
  static const resetPassword = '/reset_password';
  static const selectContactsFromTag = '/select_contacts_from_tag';
  static const wallet = '/wallet';
  static const billDetail = '/bill_detail';
  static const transfer = '/transfer';
  static const luckMoney = '/luck_money';
  static const selectedMemberList = '/luck_money/group_member_list';
  static const luckMoneyDetail = '/luck_money/luck_money_detail';
  static const luckMoneyLog = '/luck_money/luck_money_log';
  static const muteSetup = '/mute_setup';
  static const groupAc = '/group_ac';
  static const search = '/search';
  static const myQrcode = '/my_qrcode';
  static const webViewPage = '/web_view_page';
  static const addAcount = '/add_acount';
  static const accountRegister = '/account_register';
  static const checkin = '/checkin';
  static const lotteryTickets = '/lottery_tickets';
  static const prizeRecords = '/prize_records';
  static const checkinRewards = '/checkin_rewards';
  // 移除规则说明页面路由
  static const article = '/article';
  static const lotteryWheel = '/lottery_wheel';
  static const paymentMethod = '/payment_method';
}

extension RoutesExtension on String {
  String toRoute() => '/${toLowerCase()}';
}